# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - Rscript -e "print(paste('Appveyor cache skipping setting:', Sys.getenv('APPVEYOR_CACHE_SKIP_RESTORE')))"
  - git config --global user.name "travis"
  - git config --global user.email "travis@example.org"
  - Rscript -e "install.packages('xgboost', repos=c('http://dmlc.ml/drat/', 'https://cran.cnr.berkeley.edu/'), type='source')"
  - Rscript -e "source('http://bioconductor.org/biocLite.R'); biocLite(c('sva', 'genefilter'))"
  - travis-tool.sh install_deps
  - travis-tool.sh github_package jimhester/covr

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

on_success:
  - Rscript -e 'covr::codecov()'

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    _R_CHECK_FORCE_SUGGESTS_: 0
    R_ARCH: x64
    USE_RTOOLS: true ## to be able to use Remotes (i.e. packages from non-CRAN sources)
    # Run once as PR to update the appveyor cache, which should fix glmnet issue.
    APPVEYOR_CACHE_SKIP_RESTORE: true

  matrix:
    - R_VERSION: release

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

cache:
  - C:\RLibrary
